language: ruby
cache: bundler
rvm:
  - 2.3.1
notifications:
  slack:
    rooms:
      - geopin:Yfd8083hJqXxAZWZAjwQkCYt#deployment
  script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake db:test:prepare