language: ruby
cache: bundler
rvm:
  - 2.3.1
env:
  - RAILS_ENV=test
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
notifications:
  slack:
    rooms:
      - geopin:Yfd8083hJqXxAZWZAjwQkCYt#deployment
